### ISSUE TITLE
skip file types when indexing music

### ISSUE THREAD

**Issue by greentea47** [ugjka/music#3]
can you add an option to ignore defined file types when the program starts?

I have a lot of .flac, .jpg. and random .ini files in my music collection that are skipped anyway such as
INFO[04-27|16:20:34] skipping invalid file                    module=app/server file=cover.jpg
INFO[04-27|16:20:34] skipping invalid file                    module=app/server file=desktop.ini
INFO[04-27|16:20:34] skipping invalid file                    module=app/server file=AlbumArtSmall.jpg
INFO[04-27|16:20:34] skipping invalid file                    module=app/server file=AlbumArt_{0D5E074E-9562-49C9-97DB-C2F787991E56}_Large.jpg
INFO[04-27|16:20:34] skipping invalid file                    module=app/server file=AlbumArt_{0D5E074E-9562-49C9-97DB-C2F787991E56}_Small.jpg

It would be helpful to have a flag like --ignore=flac or something similar

**Comment by ugjka** [comment]
Removed invalid file logging in 3676310
